[package]
name = "xmlrust"
version = "0.1.0"
authors = ["Paulo Nuin <nuin@genedrift.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xml-rs = "0.8"
